name: Set release version

on:
  push:
    branches:
      - main

jobs:
  set-release-version:
    name: Set release version
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js 14.18.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.x'
      - name: Cache yarn directory
        id: cache-yarn-dir
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.cache-yarn-dir.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
